/* tslint:disable */
/* eslint-disable */
/**
 * starbuck api
 * starbucks api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddProductHandlerRequest
 */
export interface AddProductHandlerRequest {
    /**
     * 
     * @type {string}
     * @memberof AddProductHandlerRequest
     */
    desc: string;
    /**
     * 
     * @type {number}
     * @memberof AddProductHandlerRequest
     */
    discount: number;
    /**
     * 
     * @type {string}
     * @memberof AddProductHandlerRequest
     */
    groupId: string;
    /**
     * 
     * @type {string}
     * @memberof AddProductHandlerRequest
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof AddProductHandlerRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof AddProductHandlerRequest
     */
    price: number;
}

/**
 * Check if a given object implements the AddProductHandlerRequest interface.
 */
export function instanceOfAddProductHandlerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "desc" in value;
    isInstance = isInstance && "discount" in value;
    isInstance = isInstance && "groupId" in value;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "price" in value;

    return isInstance;
}

export function AddProductHandlerRequestFromJSON(json: any): AddProductHandlerRequest {
    return AddProductHandlerRequestFromJSONTyped(json, false);
}

export function AddProductHandlerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddProductHandlerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'desc': json['desc'],
        'discount': json['discount'],
        'groupId': json['groupId'],
        'image': json['image'],
        'name': json['name'],
        'price': json['price'],
    };
}

export function AddProductHandlerRequestToJSON(value?: AddProductHandlerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'desc': value.desc,
        'discount': value.discount,
        'groupId': value.groupId,
        'image': value.image,
        'name': value.name,
        'price': value.price,
    };
}

