/* tslint:disable */
/* eslint-disable */
/**
 * starbuck api
 * starbucks api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderResponse
 */
export interface CreateOrderResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderResponse
     */
    orderId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateOrderResponse
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderResponse
     */
    message: string;
}

/**
 * Check if a given object implements the CreateOrderResponse interface.
 */
export function instanceOfCreateOrderResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orderId" in value;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function CreateOrderResponseFromJSON(json: any): CreateOrderResponse {
    return CreateOrderResponseFromJSONTyped(json, false);
}

export function CreateOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'code': json['code'],
        'message': json['message'],
    };
}

export function CreateOrderResponseToJSON(value?: CreateOrderResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderId': value.orderId,
        'code': value.code,
        'message': value.message,
    };
}

