/* tslint:disable */
/* eslint-disable */
/**
 * starbuck api
 * starbucks api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginHandlerRequest
 */
export interface LoginHandlerRequest {
    /**
     * 
     * @type {string}
     * @memberof LoginHandlerRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof LoginHandlerRequest
     */
    userName: string;
}

/**
 * Check if a given object implements the LoginHandlerRequest interface.
 */
export function instanceOfLoginHandlerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "userName" in value;

    return isInstance;
}

export function LoginHandlerRequestFromJSON(json: any): LoginHandlerRequest {
    return LoginHandlerRequestFromJSONTyped(json, false);
}

export function LoginHandlerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginHandlerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
        'userName': json['userName'],
    };
}

export function LoginHandlerRequestToJSON(value?: LoginHandlerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'userName': value.userName,
    };
}

