/* tslint:disable */
/* eslint-disable */
/**
 * starbuck api
 * starbucks api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResponseAllOf
 */
export interface LoginResponseAllOf {
    /**
     * 
     * @type {string}
     * @memberof LoginResponseAllOf
     */
    token: string;
}

/**
 * Check if a given object implements the LoginResponseAllOf interface.
 */
export function instanceOfLoginResponseAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function LoginResponseAllOfFromJSON(json: any): LoginResponseAllOf {
    return LoginResponseAllOfFromJSONTyped(json, false);
}

export function LoginResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function LoginResponseAllOfToJSON(value?: LoginResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

