/* tslint:disable */
/* eslint-disable */
/**
 * starbuck api
 * starbucks api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderDoneHandlerRequest
 */
export interface OrderDoneHandlerRequest {
    /**
     * 
     * @type {string}
     * @memberof OrderDoneHandlerRequest
     */
    orderId: string;
}

/**
 * Check if a given object implements the OrderDoneHandlerRequest interface.
 */
export function instanceOfOrderDoneHandlerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orderId" in value;

    return isInstance;
}

export function OrderDoneHandlerRequestFromJSON(json: any): OrderDoneHandlerRequest {
    return OrderDoneHandlerRequestFromJSONTyped(json, false);
}

export function OrderDoneHandlerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDoneHandlerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
    };
}

export function OrderDoneHandlerRequestToJSON(value?: OrderDoneHandlerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderId': value.orderId,
    };
}

