/* tslint:disable */
/* eslint-disable */
/**
 * starbuck api
 * starbucks api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpgradeToVipRequest
 */
export interface UpgradeToVipRequest {
    /**
     * 
     * @type {string}
     * @memberof UpgradeToVipRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the UpgradeToVipRequest interface.
 */
export function instanceOfUpgradeToVipRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function UpgradeToVipRequestFromJSON(json: any): UpgradeToVipRequest {
    return UpgradeToVipRequestFromJSONTyped(json, false);
}

export function UpgradeToVipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpgradeToVipRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function UpgradeToVipRequestToJSON(value?: UpgradeToVipRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
    };
}

