/* tslint:disable */
/* eslint-disable */
/**
 * starbuck api
 * starbucks api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletDescribeRespAllOf
 */
export interface WalletDescribeRespAllOf {
    /**
     * 
     * @type {number}
     * @memberof WalletDescribeRespAllOf
     */
    balance: number;
}

/**
 * Check if a given object implements the WalletDescribeRespAllOf interface.
 */
export function instanceOfWalletDescribeRespAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "balance" in value;

    return isInstance;
}

export function WalletDescribeRespAllOfFromJSON(json: any): WalletDescribeRespAllOf {
    return WalletDescribeRespAllOfFromJSONTyped(json, false);
}

export function WalletDescribeRespAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletDescribeRespAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balance': json['balance'],
    };
}

export function WalletDescribeRespAllOfToJSON(value?: WalletDescribeRespAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balance': value.balance,
    };
}

