/* tslint:disable */
/* eslint-disable */
/**
 * starbuck api
 * starbucks api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletDescribeResp
 */
export interface WalletDescribeResp {
    /**
     * 
     * @type {number}
     * @memberof WalletDescribeResp
     */
    balance: number;
    /**
     * 
     * @type {number}
     * @memberof WalletDescribeResp
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof WalletDescribeResp
     */
    message: string;
}

/**
 * Check if a given object implements the WalletDescribeResp interface.
 */
export function instanceOfWalletDescribeResp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "balance" in value;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function WalletDescribeRespFromJSON(json: any): WalletDescribeResp {
    return WalletDescribeRespFromJSONTyped(json, false);
}

export function WalletDescribeRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletDescribeResp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balance': json['balance'],
        'code': json['code'],
        'message': json['message'],
    };
}

export function WalletDescribeRespToJSON(value?: WalletDescribeResp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balance': value.balance,
        'code': value.code,
        'message': value.message,
    };
}

